AWSTemplateFormatVersion: '2010-09-09'
Resources:
  SourceDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: "source-db"
      DBInstanceClass: db.t3.micro
      Engine: postgres
      MasterUsername: admin
      MasterUserPassword: MySecurePassword123
      AllocatedStorage: 20
      PubliclyAccessible: true
      DBSubnetGroupName: default

  TargetDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: "target-db"
      DBInstanceClass: db.t3.micro
      Engine: mysql
      MasterUsername: admin
      MasterUserPassword: MySecurePassword123
      AllocatedStorage: 20
      PubliclyAccessible: true
      DBSubnetGroupName: default
