AWSTemplateFormatVersion: "2010-09-09"
Description: "Launch a Instance"
Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
  VpcId:
    Type: String
    Default: 
  ImageId:
    Type: String
    Default: ami-004d18eae1ef10a65
  SubnetId:
    Type: String
    Default: 
Resources:
    SSMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AmazonSSMManagedInstanceRole  # Optional: Set a custom role name
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com  # EC2 assumes this role
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore 
  EC2InstanceProfile:  
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref SSMRole

  MyEC2Instance: 
    Type: AWS::EC2::Instance
    Properties: 
      IAMInstanceProfile: !Ref EC2InstanceProfile
      InstanceType: !Ref InstanceType
      ImageId: !Ref ImageId
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
        - !GetAtt SG.GroupId
  SG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0