AWSTemplateFormatVersion: "2010-09-09"
Description: "Create a role us to assume create a resource for access"
Parameters:
  BucketName:
    Type: String
    Default: "sts-s3-ab-165432"
    Description: "Name of the s3"
Resources:
  StsRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - s3.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: 
                - !Sub "arn:aws::s3:::${BucketName}"
                - !Sub "arn:aws::s3:::${BucketName}/*"
                